version: '3'
services:
  app:
    container_name: "gosample_app"
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    volumes:
      - "./app:/go/src/app"
    tty: true
    ports:
      - "8080:8080"    
  db:
    container_name: "gosample_db"
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
        # 永続化することでコンテナ削除してもOK
        #- "./docker/pgsql/data:/var/lib/postgresql/data"
        # dbスクリプト
        #- "./docker/pgsql/init:/docker-entrypoint-initdb.d"
    networks:
     - golang

networks:
  golang:
    driver: "bridge"
